// Generated by Selenium IDE
package Regresstion_testing;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.beust.jcommander.internal.Console;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class CreateNewClient {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  WebDriverManager.edgedriver().setup();
      driver = new EdgeDriver();
      js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
//    driver.quit();
  }
  @Test
  public void oAP2041() {
	  
	/*
	 * Creates a client
	 */
	driver.get("http://intra.stage.oacis.children.gov.on.ca/Main.aspx");
    driver.manage().window().setSize(new Dimension(1696, 1036));
    driver.findElement(By.id("ctlPrimaryNav_lnkClient")).click();
    driver.findElement(By.id("ctlStandardOperations_lnkNew")).click();
    driver.findElement(By.id("ctlClientContent_txtLastName")).click();
    driver.findElement(By.id("ctlClientContent_txtLastName")).sendKeys("Max Johnson");
    driver.findElement(By.id("ctlClientContent_txtFirstName")).sendKeys("Steve F");
    driver.findElement(By.id("ctlClientContent_ctlDob_txtDate")).click();
    driver.findElement(By.id("ctlClientContent_ctlDob_txtDate")).sendKeys("2010/09/08");
    driver.findElement(By.id("ctlStandardOperations_lnkSave")).click();
    driver.findElement(By.id("ctlStandardOperations_lnkSave")).click();

  }
}
