package getting_started;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class RecordedTest1 {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 //driver = new ChromeDriver();
 
	// WebDriverManager.edgedriver().setup();
   //  driver = new EdgeDriver();
	
 
 
//System.setProperty("webdriver.ie.driver","C:\\Users\\OKeeffKy\\SeleniumDrivers\\32bit\\IEDriverServer.exe");
		InternetExplorerOptions ieOptions = new InternetExplorerOptions();
		//ieOptions.setCapability("", false);
		
		ieOptions.attachToEdgeChrome();
		ieOptions.withEdgeExecutablePath("C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe");
       //ieOptions.introduceFlakinessByIgnoringSecurityDomains();//IntroduceInstabilityByIgnoringProtectedModeSettings = true;

		//WebDriver 
		driver =new InternetExplorerDriver(ieOptions);
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		js = (JavascriptExecutor) driver;
		 vars = new HashMap<String, Object>();
		
		//driver.get("http://intra.stage.oacis.children.gov.on.ca/");
			//driver.quit();
}
@After
public void tearDown() {
 //driver.quit();
}
@Test
public void test1() throws InterruptedException {
 driver.get("http://intra.stage.oacis.children.gov.on.ca/");
 driver.manage().window().setSize(new Dimension(945, 1020));
 driver.findElement(By.id("ctlQueryBox_txtQuery")).click();
 driver.findElement(By.id("ctlQueryBox_txtQuery")).sendKeys("kyle");
 driver.findElement(By.id("ctlQueryBox_txtQuery")).sendKeys(Keys.ENTER);
 driver.findElement(By.id("ctlClientSearch_dgdClientSearch__ctl2_lblApplicantName")).click();
 driver.findElement(By.id("ctlPageNav_lnkApplications")).click();
 driver.findElement(By.id("ctlStandardOperations_lnkNew")).click();
 driver.findElement(By.id("ctlAppContent_txtApplicantLastName")).click();

 driver.findElement(By.cssSelector("table:nth-child(15) > tbody > tr")).click();
 driver.findElement(By.id("ctlAppContent_txtApplicantLastName")).sendKeys("jkhk");
 driver.findElement(By.id("ctlAppContent_txtApplicantFirstName")).click();
 driver.findElement(By.id("ctlAppContent_txtApplicantFirstName")).sendKeys("kjh");
 driver.findElement(By.id("ctlAppContent_ctlApplicantDob_txtDate")).click();
 driver.findElement(By.id("ctlAppContent_ctlApplicantDob_imgCal")).click();
 driver.findElement(By.id("ctlAppContent_ctlApplicantDob_imgCal")).click();
 driver.findElement(By.id("ctlAppContent_ctlApplicantDob_txtDate")).click();
 driver.findElement(By.id("ctlAppContent_ctlApplicantDob_txtDate")).sendKeys("01-jun-2019");
 driver.findElement(By.id("ctlAppContent_ctlApplicantDob_txtDate")).sendKeys(Keys.ENTER);
 driver.findElement(By.id("ctlAppContent_panelApplicant1")).click();
 
}
}
