// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestcreateClientTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testcreateClient() {
    driver.get("http://intra.stage.oacis.children.gov.on.ca/Main.aspx");
    driver.manage().window().setSize(new Dimension(1050, 718));
    driver.findElement(By.id("ctlQueryBox_txtQuery")).click();
    driver.findElement(By.id("ctlPrimaryNav_lnkClient")).click();
    driver.findElement(By.id("ctlStandardOperations_lnkNew")).click();
    driver.findElement(By.id("ctlClientContent_txtLastName")).click();
    driver.findElement(By.id("ctlClientContent_txtLastName")).sendKeys("TestJunitLast");
    driver.findElement(By.id("ctlClientContent_txtFirstName")).click();
    driver.findElement(By.id("ctlClientContent_txtFirstName")).sendKeys("TestJunitFirst");
    driver.findElement(By.id("ctlClientContent_ctlDob_imgCal")).click();
    driver.findElement(By.id("ctlClientContent_ctlDob_txtDate")).click();
    driver.findElement(By.id("ctlClientContent_ctlDob_txtDate")).sendKeys("2004/04/02");
    driver.findElement(By.id("ctlStandardOperations_lnkSave")).click();
  }
}
